# Generated by Django 5.0.4 on 2024-04-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_login',
            fields=[
                ('user_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=4)),
                ('gmail', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='company_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_round', models.IntegerField(null=True)),
                ('second_round', models.IntegerField(null=True)),
                ('gmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pat1.student_login')),
            ],
        ),
    ]
